services:
  service:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    container_name: golang-backend
    networks:
      - integration
    # environment:
    #   POSTGRES_HOST: postgres
    #   POSTGRES_USER: postgres_user
    #   POSTGRES_PASSWORD: postgres_password
    #   POSTGRES_DB: postgres_db
    #   MONGO_HOST: mongo
    #   REDIS_HOST: redis
#    depends_on:
#      - postgres
#      - mongo
#      - redis
    ports:
      - "8080:8080"
    logging:
      driver: none

  tester:
    build:
      context: ../../
      dockerfile: docker/test-integration/Dockerfile
    container_name: golang-backend-test
    networks:
      - integration
    depends_on:
      - service
    logging:
      driver: none

#  postgres:
#    image: postgres:latest
#    container_name: postgres
#    restart: always
#    environment:
#      POSTGRES_USER: postgres_user
#      POSTGRES_PASSWORD: postgres_password
#      POSTGRES_DB: postgres_db
#    networks:
#      - integration
#    logging:
#      driver: none
#
#  mongo:
#    image: mongo:latest
#    container_name: mongo
#    restart: always
#    networks:
#      - integration
#    logging:
#      driver: none
#
#  redis:
#    image: redis:latest
#    container_name: redis
#    restart: always
#    networks:
#      - integration
#    logging:
#      driver: none

networks:
  integration:
    driver: bridge